config/routes.rb
RudysWebsite::Application.routes.draw do

  put "/contact_infos/update" => 'contact_infos#update'

  get "/admin" => 'admin#index'
  get "/admin/posts" => 'admin#posts'
  get "/admin/display" => 'admin#display'
  get "/admin/orders" => 'admin#orders'

  devise_for :users

  root :to => 'static_pages#home'

  get "/contact" => 'contact_infos#show'
  get "/contact/edit" => 'contact_infos#edit'

  resources :home_posts
  resources :users
  resources :patterns

  match "patterns/:title" => "pattern#show"

end

app/models/about_info.rb
class AboutInfo < ActiveRecord::Base
  attr_accessible :description, :image
end

app/models/contact_info.rb
class ContactInfo < ActiveRecord::Base
  attr_accessible :address, :email, :name, :phone
end

app/models/home_front.rb
class HomeFront < ActiveRecord::Base
  attr_accessible :description, :pattern_id, :title
  belongs_to :pattern
end

app/models/home_post.rb
class HomePost < ActiveRecord::Base
  attr_accessible :post, :user_id
  belongs_to :user
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :user_id, :pattern_id, :qty
  belongs_to :user
  belongs_to :pattern
end

app/models/pattern.rb
class Pattern < ActiveRecord::Base
  attr_accessible :description, :image, :price, :title
  has_many :pattern_posts
  has_many :orders

  mount_uploader :image, PatternUploader

  #For no id, use friendly_id gem. Watch Railscast #314.
  def to_param
    title
  end
end

app/models/pattern_post.rb
class PatternPost < ActiveRecord::Base
  attr_accessible :user_id, :pattern_id, :image
  belongs_to :user
  belongs_to :pattern
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :avatar, :admin, :remote_avatar_url
  
  has_many :pattern_posts
  has_many :home_posts
  has_many :orders

  mount_uploader :avatar, AvatarUploader

  validates :name, :presence => true
  validates :email, :presence => true
  # validates :password, :presence => true
  # validates :password_confirmation, :presence => true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
  def index
  end

  def posts
  end

  def display
  end

  def orders
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_footer

  def set_footer
    @footer = Pattern.first(6)
  end

end

app/controllers/contact_infos_controller.rb
class ContactInfosController < ApplicationController
  def show
    @info = ContactInfo.first
  end

  def edit
    @info = ContactInfo.first
  end

  def update
    info = ContactInfo.find_by_name(params["contact_info"]["name"])
    if info.update_attributes(params["contact_info"])
      flash[:notice] = "User successfully updated"
      redirect_to "/contact"
    else
      render :action => "show", :id => :info
    end
  end

end

app/controllers/home_posts_controller.rb
class HomePostsController < ApplicationController

  def index
    @home_posts = HomePost.all 

    respond_to do |format|
      format.js
    end
  end

  def show
  end

  def new
    @post = HomePost.new
  end

  def create
    post = HomePost.new(params[:home_post])
    post.save
    redirect_to :root
  end

  def edit
    @post = HomePost.find(params[:id])
  end

  def update
    post = HomePost.find(params[:id])
    if post.update_attributes(params[:home_post])
      flash[:notice] = "Post successfully updated"
      redirect_to :root
    else
      flash[:notice] = "Post did not update"
      render :action => "edit", :id => :post
    end
  end

  def destroy
    @hp = HomePost.find(params[:id])
    @hp_id = @hp.id
    @hp.destroy

    @home_posts = HomePost.all
    respond_to do |format|
      format.js
    end
  end

  def refresh
    @home_posts = HomePost.all

    respond_to do |format|
      format.js
    end
  end
end

app/controllers/patterns_controller.rb
class PatternsController < ApplicationController

  def index
    @patterns = Pattern.all
  end

  def show
    @pattern = Pattern.find_by_title(params[:id])
  end

  def new
    @pattern = Pattern.new
  end

  def create
    pattern = Pattern.new(params[:pattern])
    pattern.save
    redirect_to patterns_path
  end

  def edit
    @pattern = Pattern.find(params[:id])
  end

  def update
    pattern = Pattern.find_by_title(params[:id])
    if pattern.update_attributes(params[:pattern])
      flash[:notice] = "User successfully updated"
      redirect_to patterns_path
    else
      render :action => "show", :title => :pattern
    end
  end

  def destroy
    Pattern.find(params[:id]).destroy
    redirect_to patterns_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @home_posts = HomePost.order("created_at DESC").last(4)
    @home_front = Pattern.find HomeFront.first.pattern_id
  end

  def destroy
    @hp = HomePost.find(params[:id]).destroy
    @hp_id = @hp.id
    @hp.destroy

    # respond_with(@hp_id, location: :root)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if user.update_attributes(params[:user])
      flash[:notice] = "User successfully updated"
      redirect_to user_path(params[:id])
    else
      render :action => "show", :id => :user
    end
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_infos_helper.rb
module ContactInfosHelper
end

app/helpers/home_posts_helper.rb
module HomePostsHelper
end

app/helpers/patterns_helper.rb
module PatternsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contact_infos/edit.html.erb
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>
<%= form_for @info, :url => { :action => "update" } do |f| %>

    <p><%= f.label :name %></p>
    <p><%= f.text_field :name %></p>

    <p><%= f.label :address %></p>
    <p><%= f.text_area :address %></p>

    <p><%= f.label :phone %></p>
    <p><%= f.text_field :phone %></p>

    <p><%= f.label :email %></p>
    <p><%= f.text_field :email %></p>

  <%= f.submit "Update" %>
<% end %>

app/views/contact_infos/show.html.erb
<h1>Contact Info</h1>
<div id= "middle">
  <div id="main_info">
    <%= image_tag "waste_not_want_not.jpg", :id => "head_shot" %>
    <section id="contact_info">
      <p><%= @info.name %></p>
      <p><%= @info.address %></p>
      <p><%= @info.phone %></p>
      <p><%= @info.email %></p>
      <% if current_user.try(:admin?) %>
        <%= link_to "Edit", "contact/edit" %>
      <% end %>
    </section>
  </div>
</div>

app/views/home_posts/_post_partial.html.erb
<section id="posts">
      <% if current_user.try(:admin?) %>
        <%= link_to "Create new Post", new_home_post_path %>
      <% end %>
      <% @home_posts.each do |post| %>
      <div class="post" id="<%= "post-#{post.id}" %>">
        <span><%= post.post %></span>
        <div>
        <span class="timestamp">
          <%= post.created_at.stamp("March 1, 1999") %>
        </span>
        <% if current_user.try(:admin?) %>
        <span class="post-links">
          <%= link_to "Edit", edit_home_post_path(post) %>
          <%= link_to "Delete", post, method: :delete, remote: true %>
        </span>
        <% end %>
        </div>
      </div>
      <br>
      <% end %>
    </section>

app/views/home_posts/destroy.js.erb
$("#post-<%= @hp_id %>").fadeOut().remove();

app/views/home_posts/edit.html.erb
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>
<%= form_for @post, :url => { :action => "update" } do |f| %>

    <p><%= f.label :post %></p>
    <p><%= f.text_area :post %></p>

  <%= f.submit "Update" %>
<% end %>

app/views/home_posts/index.html.erb
<h1>Posts</h1><% @home_posts.each do |post| %>
  <div class="posts">
    <p><%= post.post %></p>
    <p>
      <%= link_to "Edit", edit_home_post_path(post.id) %>
      <%= link_to "Delete", home_post_path(post.id), :confirm => "are you sure?", :method => :delete %>
    </p>
  </div>
  <br>
<% end %>

app/views/home_posts/new.html.erb
<%= form_for @post, :url => { :action => "create" } do |f| %>

    <p><%= f.label :post %></p>
    <p><%= f.text_area :post %></p>

    <%= f.hidden_field :user_id, :value => current_user.id %>

  <%= f.submit "Update" %>
<% end %>

app/views/home_posts/refresh.js.erb
alert("help")
$("#posts").html(<%= j render "post_partial", locals: {home_posts: @home_posts} %>);

app/views/home_posts/show.html.erb
<h1>Posts#show,</h1>
<p>Find me in app/views/posts/show,.html.erb</p>

app/views/home_posts/update.html.erb
<h1>Posts#update,</h1>
<p>Find me in app/views/posts/update,.html.erb</p>

app/views/patterns/edit.html.erb
<%= form_for @pattern, :html => {:multipart => true} do |f| %>
  
  <%= image_tag(@pattern.image_url(:full))  %>
  <p><%= "Current File is: #{@pattern.image_url}" %></p>
  <p><%= f.file_field :image %></p>

  <p><%= f.label :title %></p>
  <p><%= f.text_field :title %></p>

  <p><%= f.label :description %></p>
  <p><%= f.text_area :description %></p>

  <%= f.submit "Add" %>
  
<% end %>

app/views/patterns/index.html.erb
<%= javascript_include_tag "pattern/patterns_index.js" %>
<div id= "patterns_area">
  <div id="pattern_info">
    <% if current_user.try(:admin?) %>
      <%= link_to "Create New Pattern", new_pattern_path %>
    <% end %>
    <% @patterns.each do |pattern| %>
      <div class="pattern">
        <%= link_to image_tag(pattern.image_url(:full)), pattern_path(pattern.title) %>
        <div class="pattern_title">
          <h2><%= link_to "#{pattern.title}", pattern_path(pattern.title) %></h2>
        </div>
        <div class="pattern_description">
          <p><%= pattern.description || "No description given." %></p>
        </div>
        <% if current_user.try(:admin?) %>
          <%= link_to "Edit", edit_pattern_path(pattern.id) %>
          <%= link_to "Delete", pattern_path(pattern.id), :confirm => "are you sure?", :method => :delete %>
        <% end %>
      </div>
      <br>
    <% end %>
  </div>
</div>

app/views/patterns/new.html.erb
<%= form_for @pattern , :url => { action: "create" }, :html => {:multipart => true} do |f| %>
  
  <p><%= f.label :title %></p>
  <p><%= f.text_field :title %></p>

  <p><%= f.label :description %></p>
  <p><%= f.text_area :description %></p>

  <p><%= f.file_field :image %></p>

  <%= f.submit "Add" %>
  
<% end %>

app/views/patterns/show.html.erb
<div class="pattern">
  <%= image_tag @pattern.image_url(:full) if @pattern.image? %>
  <div class="pattern_title">
    <h2><%= "#{@pattern.title} Pattern" %></h2>
  </div>
  <div class="pattern_description">
    <p><%= @pattern.description || "No description given." %></p>
  </div>
</div>

app/views/static_pages/_post_partial.html.erb
<section id="posts">
  <% if current_user.try(:admin?) %>
    <%= link_to "Create new Post", new_home_post_path %>
  <% end %>
  <% @home_posts.each do |post| %>
  <div class="post" id="<%= "post-#{post.id}" %>">
    <span><%= post.post %></span>
    <div>
    <span class="timestamp">
      <%= post.created_at.stamp("March 1, 1999") %>
    </span>
    <% if current_user.try(:admin?) %>
    <span class="post-links">
      <%= link_to "Edit", edit_home_post_path(post) %>
      <%= link_to "Delete", post, method: :delete, remote: true, confirm: "Are you sure you want to delete this post?" %>
    </span>
    <% end %>
    </div>
  </div>
  <br>
  <% end %>
</section>

app/views/static_pages/contact.html.erb
<div id= "middle">
  <div id="main_info">
    <img id="head_shot" src="waste_not_want_not.jpg">
    <section id="contact_info">
      <p>Barb Mclean</p>
      <p>555 Juniper Lane</p>
      <p>Toledo, OH 55555</p>
      <p>(555)555-5555</p>
      <p>mommamclean@gmail.com</p>
      <% if current_user.try(:admin?) %>
        <%= link_to "Edit", "/contact/edit" %>
      <% end %>
    </section>
  </div>
</div>

app/views/static_pages/home.html.erb
<div id= "middle">
  <section id="slideshow">
    <a href="#"><%= link_to image_tag(@home_front.image_url(:full)), pattern_path(@home_front.title) %></a>
    <p><%= @home_front.title %></p>
    <p><%= @home_front.description %></p>
  </section>
  <div id="main_info">
    <section id="greeting">
      <h1>Modern Patterns</h1>
        <p>Welcome to Rudy Lynn's Quilts. Please browse the patterns both modern and traditional. If you have and questions, please visit the Contact page.</p>
    </section>
    
    <%= render "post_partial", remote: true %>

  </div>
</div>
  

app/views/static_pages/refresh.js.erb
// alert("help")
$("#posts").html(<%= j render "post_partial" %>);

app/views/users/edit.html.erb
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>
<%= form_for @user do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.text_field :password %>
  </p>
  <%= f.submit "Update" %>
<% end %>

app/views/users/index.html.erb
<h2>Users</h2>

<% @users.each do |user| %>
  <p><%= link_to "#{user.name}", user_path(user) %></p>
<% end %>

app/views/users/show.html.erb
<h1>Your Account</h1>

<p><%= @user.name %></p>
<p><%= @user.email %></p>

<%= link_to "Edit", edit_user_path(@user.id) %>